project:
  type: book
  resources: 
    - "figures/*dark*"

filters:
  - shinylive
  
format:
  html:
    toc: true
    theme:
      light: [simplex, includes/aml4td.scss]
      dark:  [cyborg,  includes/aml4td-dark.scss]   
    mainfont: 'Libre Franklin'
    fig-width: 6
    fig-height: 4.25
    fig-align: center
    tbl-cap-location: bottom
    fig-cap-location: bottom
    keep-md: false

include-after-body:
  text: |
    <script type="application/javascript" src="../includes/updateImageSrc.js"></script>
    
execute:
  freeze: auto
  keep-md: false
  # turn these on during development
  # message: false
  # warning: false
  echo: false

knitr: 
  opts_chunk: 
    dev: [lightsvglite, darksvglite]
    fig.ext: [light.svg, dark.svg]  

resources:
  - CNAME

book:
  title: "Applied Machine Learning for Tabular Data"
  author: 
  - name: Max Kuhn
    orcid: 0000-0003-2402-136X
    email: mxkuhn@gmail.com
  - name: Kjell Johnson
    orchid: 0000-0003-4260-9634
    email: kjell@stattenacity.com
  date: last-modified
  date-format: YYYY-MM-DD
  site-url: https://aml4td.org
  repo-url: https://github.com/aml4td/website/
  sharing: [twitter, facebook, linkedin]  
  sidebar:
      style: "docked"
      title: " "
  reader-mode: true
  bread-crumbs: false
  chapters:
  - index.qmd
  - chapters/news.qmd
  - chapters/contributing.qmd  
  - chapters/introduction.qmd
  # - chapters/whole-game.qmd
  - part: "Preparation"
  - chapters/initial-data-splitting.qmd
  # - chapters/numeric-predictors.qmd 
  # - chapters/categorical-predictors.qmd    
  # - chapters/embeddings.qmd  
  # - chapters/interactions-nonlinear.qmd
  # - part: "Optimization"
  # - chapters/overfitting.qmd  
  - part: "Classification"  
  - part: "Regression"  
  - part: "Characterization"  
  - part: "Finalization"  

bibliography: includes/references_linked.bib
csl: includes/chicago-author-date-inline.csl

