---
knitr:
  opts_chunk:
    cache.path: "../_cache/cls-metrics/"
---

# Characterizing Classification Models {#sec-cls-metrics}

```{r}
#| label: cls-metrics-setup
#| include: false

source("../R/_common.R")

# ------------------------------------------------------------------------------

library(tidymodels)

# ------------------------------------------------------------------------------
# set options

tidymodels_prefer()
theme_set(theme_transparent())

set_options()

# ------------------------------------------------------------------------------
# load data 

```

## Class Distributions  {#sec-cls-distributions}

## Choosing Appropriate Metrics {#sec-metric-information}

## Example Data: Poisonous Mushrooms {#sec-mushrooms}

## Assessing Hard Class Predictions {#sec-cls-hard-metrics}

## Metrics for Two Classes {#sec-cls-two-classes}

## Weighted Performance Metrics {#sec-cls-metrics-wts}

## Evaluating Probabilistic Predictions {#sec-cls-metrics-soft}

### Cross-Entropy {#sec-cross-entropy}

### Brier Scores {#sec-brier}

### Reciever Operating Characteristic Curves {#sec-roc}

### Precision-Recall Curves {#sec-pr}

### Comparing ROC and PR Curves {#sec-compare-roc-pr}

### Gain Charts {#sec-gain}

## Measuring and Improving Calibration {#sec-calibration}

## Ordered Categories {#sec-ordered-categories}

## Multi-Objective Assessments {#sec-multi-objectives}

## Chapter References {.unnumbered}

