# News {.unlisted .unnumbered}

## Changelog {.unlisted .unnumbered}

### TBD

New chapters were added for: iterative optimization, feature selection, and model comparisons. These finish Part 3. 

Part 4 was started with a chapter on classification metrics. 

Other updates of note: 

- A new section was added to @sec-overfitting on permutation estimates. 

- Links were added at the end of sections where there is a corresponding computing supplement. For now, only R code is available using the emoji {{< fa brands r-project >}}.
 
- Some chapter/section URLs have changed. 

### 2024-10-01

Enabled google analytics.

### 2024-09-23

Chapter 4 is now on missing data, bumping subsequent chapter numbers. 

New chapters on resampling and grid search are now online. 

### 2024-06-17  {.unlisted .unnumbered}

Several new chapters on embeddings, splines/interactions/discretization, and overfitting. Also, shinylive is used for interactive visualizations of concepts.

### 2024-01-02  {.unlisted .unnumbered}

Fixed various typos. 

### 2023-12-21  {.unlisted .unnumbered}

Typo fix on main page. 

### 2023-12-19  {.unlisted .unnumbered}

Small updates. 

Updated snapshot.

The background color of premade outputs has been changed to the pages background color ([#16](https://github.com/aml4td/website/pull/16)).


### 2023-12-11  {.unlisted .unnumbered}

No new content. 

Updated snapshot. 

Includes new Google Scholar links for articles ([#8](https://github.com/aml4td/website/pull/8))

### 2023-11-17  {.unlisted .unnumbered}

Updated renv snapshot. 

### 2023-10-09  {.unlisted .unnumbered}

First committed versions. 


