<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Working with Categorical Predictors – Applied Machine Learning for Tabular Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/embeddings.html" rel="next">
<link href="../chapters/numeric-predictors.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c4c45efb52384bb089fdf85ece132d3c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-7T996NL20Z"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-7T996NL20Z', { 'anonymize_ip': true});
</script>
<link href="https://cdn.jsdelivr.net/npm/pseudocode@latest/build/pseudocode.min.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span id="sec-categorical-predictors" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Working with Categorical Predictors</span></span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../"></a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/aml4td/website/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/news.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">News</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/contributing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contributing</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/whole-game.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The Whole Game</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Preparation</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/initial-data-splitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Initial Data Splitting</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/missing-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Missing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/numeric-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transforming Numeric Predictors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/categorical-predictors.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Working with Categorical Predictors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/embeddings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Embeddings</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/interactions-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Interactions and Nonlinear Features</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Optimization</span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/overfitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Overfitting</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/resampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Measuring Performance with Resampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/grid-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Grid Search</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Classification</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Regression</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Characterization</span></span>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">Finalization</span></span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-hotel-rates" id="toc-sec-hotel-rates" class="nav-link active" data-scroll-target="#sec-hotel-rates"><span class="header-section-number">6.1</span> Example Data: Daily Hotel Rates</a></li>
  <li><a href="#sec-indicators" id="toc-sec-indicators" class="nav-link" data-scroll-target="#sec-indicators"><span class="header-section-number">6.2</span> Simple Indicator Variables</a></li>
  <li><a href="#sec-novel-categories" id="toc-sec-novel-categories" class="nav-link" data-scroll-target="#sec-novel-categories"><span class="header-section-number">6.3</span> Novel Categories</a></li>
  <li><a href="#sec-high-cardinality" id="toc-sec-high-cardinality" class="nav-link" data-scroll-target="#sec-high-cardinality"><span class="header-section-number">6.4</span> Predictors with Many Values</a>
  <ul class="collapse">
  <li><a href="#sec-other" id="toc-sec-other" class="nav-link" data-scroll-target="#sec-other"><span class="header-section-number">6.4.1</span> “Othering”</a></li>
  <li><a href="#sec-feature-hashing" id="toc-sec-feature-hashing" class="nav-link" data-scroll-target="#sec-feature-hashing"><span class="header-section-number">6.4.2</span> Feature Hashing</a></li>
  <li><a href="#sec-effect-encodings" id="toc-sec-effect-encodings" class="nav-link" data-scroll-target="#sec-effect-encodings"><span class="header-section-number">6.4.3</span> Effect Encodings</a></li>
  <li><a href="#sec-combining-categories" id="toc-sec-combining-categories" class="nav-link" data-scroll-target="#sec-combining-categories"><span class="header-section-number">6.4.4</span> Supervised Combining of Categories</a></li>
  </ul></li>
  <li><a href="#encodings-for-ordinal-predictors" id="toc-encodings-for-ordinal-predictors" class="nav-link" data-scroll-target="#encodings-for-ordinal-predictors"><span class="header-section-number">6.5</span> Encodings for Ordinal Predictors</a></li>
  <li><a href="#chapter-references" id="toc-chapter-references" class="nav-link" data-scroll-target="#chapter-references">Chapter References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span id="sec-categorical-predictors" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Working with Categorical Predictors</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This chapter will discuss tools for handling predictor variables that are not measured on a strict numeric scale. For example, the building type and neighborhood variables are qualitative in the Ames housing data. The possible values of qualitative predictors are often called categories or levels (which will be used interchangeably here).</p>
<p>Why would we need to modify this type of predictor? First, most mathematical models require information to be numbers. We’ll need a method to convert qualitative data effectively to some quantitative format. This is an encoding problem; we are finding another representation of our predictor data. There are various tools for converting qualitative data, ranging from simple indicator variables (a.k.a. dummy variables) to more statistically sophisticated tools. These are the focus of this chapter.</p>
<p>Second, there are other circumstances where simplifying or transforming categorical predictors might be advantageous. These are usually related to exceptional situations, such as when there are many possible values (i.e., high cardinality) or infrequently occurring values. Techniques to address these issues are also discussed.</p>
<p>As implied above, some modeling techniques can take the categorical predictors in their natural form. These include tree- or rule-based models, naive Bayes models, and others. In this book’s third and fourth parts, we’ll discuss how certain models naturally handle categorical variables in their respective sections.</p>
<p>To begin, the primary data set used in this chapter is introduced.</p>
<section id="sec-hotel-rates" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-hotel-rates"><span class="header-section-number">6.1</span> Example Data: Daily Hotel Rates</h2>
<p><span class="citation" data-cites="ANTONIO201941">Antonio, de Almeida, and Nunes (<a href="#ref-ANTONIO201941" role="doc-biblioref">2019</a>)</span> describe a data set with booking records from two Portuguese hotels. There are numerous variables in the data related to the</p>
<ul>
<li>Reservation: room type, date, meal plan, etc.,</li>
<li>Booking method: agent, distribution channel, etc.,</li>
<li>Customer: type, number of children staying, country of origin, etc.</li>
</ul>
<p>In addition, there are several qualitative variables: customer type, market segment, room type, etc.</p>
<p>We’ll analyze these data in various ways (especially in <span class="quarto-unresolved-ref">?sec-reg-linear</span> to <span class="quarto-unresolved-ref">?sec-reg-summary</span> where they are used as a case study). Our goal is to predict the average daily rate (ADR, i.e., the average cost in euros) from one of the two hotels in the original data.</p>
<p>There were 15,402 bookings for the <em>resort hotel</em>. An initial two-way split was used:</p>
<ul>
<li>The training set contains 11,551 (75%) bookings whose arrivals are between 2016-07-02 and 2017-05-15.</li>
<li>The remaining 25% were used as the test set with 3,851 bookings (between 2017-05-15 to 2017-08-31).</li>
</ul>
<p>This chapter will use these data to demonstrate how qualitative data, such as the booking agent’s name or company, can be converted into quantitative information that many models require.</p>
</section>
<section id="sec-indicators" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="sec-indicators"><span class="header-section-number">6.2</span> Simple Indicator Variables</h2>
<p>As a simple example, consider the customer type predictor with categories: “contract”, “group”, “transient”, and “transient (party)”. What would we do if a model required these data to be numeric? There is no natural ordering to these values, so giving the models integer values (e.g., contract = 1.0, group = 2.0, etc.) would be erroneous since that implies a scale for these values. Instead, it is common to create multiple binary columns (numeric with zeros or ones) representing the occurrence of specific values. These are called <strong>indicator columns</strong> or sometimes <strong>dummy variables</strong>.</p>
<p><a href="#tbl-indicators" class="quarto-xref">Table&nbsp;<span>6.1</span></a> shows how this works for the customer type. The rows depict the possible values in the data, while the columns are the resulting features used in place of the original column. This table uses the most common indicator encoding method called <em>reference cell</em> parameterization (also called a <em>treatment contrast</em>). First, a category is chosen as the reference value. In <a href="#tbl-indicators" class="quarto-xref">Table&nbsp;<span>6.1</span></a>, the first alpha-numeric value is used (<code>"contract"</code>), but this is an arbitrary choice. After this, we create separate columns for all possible values except for the reference value. Each of these columns has a value of one when the data matches the column for that value (and is zero otherwise).</p>
<div class="cell" data-layout-align="center">
<div id="tbl-indicators" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-indicators-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="lhmcyxqzvc" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#lhmcyxqzvc table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#lhmcyxqzvc thead, #lhmcyxqzvc tbody, #lhmcyxqzvc tfoot, #lhmcyxqzvc tr, #lhmcyxqzvc td, #lhmcyxqzvc th {
  border-style: none;
}

#lhmcyxqzvc p {
  margin: 0;
  padding: 0;
}

#lhmcyxqzvc .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: 50%;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#lhmcyxqzvc .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#lhmcyxqzvc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#lhmcyxqzvc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#lhmcyxqzvc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lhmcyxqzvc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lhmcyxqzvc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lhmcyxqzvc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#lhmcyxqzvc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#lhmcyxqzvc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#lhmcyxqzvc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#lhmcyxqzvc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#lhmcyxqzvc .gt_spanner_row {
  border-bottom-style: hidden;
}

#lhmcyxqzvc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#lhmcyxqzvc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#lhmcyxqzvc .gt_from_md > :first-child {
  margin-top: 0;
}

#lhmcyxqzvc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#lhmcyxqzvc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#lhmcyxqzvc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#lhmcyxqzvc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#lhmcyxqzvc .gt_row_group_first td {
  border-top-width: 2px;
}

#lhmcyxqzvc .gt_row_group_first th {
  border-top-width: 2px;
}

#lhmcyxqzvc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lhmcyxqzvc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#lhmcyxqzvc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#lhmcyxqzvc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lhmcyxqzvc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lhmcyxqzvc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#lhmcyxqzvc .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#lhmcyxqzvc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#lhmcyxqzvc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lhmcyxqzvc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lhmcyxqzvc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lhmcyxqzvc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lhmcyxqzvc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lhmcyxqzvc .gt_left {
  text-align: left;
}

#lhmcyxqzvc .gt_center {
  text-align: center;
}

#lhmcyxqzvc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#lhmcyxqzvc .gt_font_normal {
  font-weight: normal;
}

#lhmcyxqzvc .gt_font_bold {
  font-weight: bold;
}

#lhmcyxqzvc .gt_font_italic {
  font-style: italic;
}

#lhmcyxqzvc .gt_super {
  font-size: 65%;
}

#lhmcyxqzvc .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#lhmcyxqzvc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#lhmcyxqzvc .gt_indent_1 {
  text-indent: 5px;
}

#lhmcyxqzvc .gt_indent_2 {
  text-indent: 10px;
}

#lhmcyxqzvc .gt_indent_3 {
  text-indent: 15px;
}

#lhmcyxqzvc .gt_indent_4 {
  text-indent: 20px;
}

#lhmcyxqzvc .gt_indent_5 {
  text-indent: 25px;
}

#lhmcyxqzvc .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#lhmcyxqzvc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="customer-type" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">customer type</th>
<th colspan="3" id="Indicator Columns" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
Indicator Columns
</div></th>
</tr>
<tr class="gt_col_headings even">
<th id="group" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">group</th>
<th id="transient" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">transient</th>
<th id="transient-party" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">transient party</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="customer type">contract</td>
<td class="gt_row gt_right" headers="group">0</td>
<td class="gt_row gt_right" headers="transient">0</td>
<td class="gt_row gt_right" headers="transient party">0</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="customer type">group</td>
<td class="gt_row gt_right" headers="group">1</td>
<td class="gt_row gt_right" headers="transient">0</td>
<td class="gt_row gt_right" headers="transient party">0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="customer type">transient</td>
<td class="gt_row gt_right" headers="group">0</td>
<td class="gt_row gt_right" headers="transient">1</td>
<td class="gt_row gt_right" headers="transient party">0</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="customer type">transient party</td>
<td class="gt_row gt_right" headers="group">0</td>
<td class="gt_row gt_right" headers="transient">0</td>
<td class="gt_row gt_right" headers="transient party">1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-indicators-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Indicator columns produced from a categorical column using a reference cell parameterization.
</figcaption>
</figure>
</div>
</div>
<p>The rationale for excluding one column is that you can infer the reference value if you know the values of all of the existing indicator columns<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Including all possible indicator columns embeds a redundancy in the data. As we will see shortly, data that contain this type of redundancy pose problems for some models like linear regression.</p>
<p>Before moving on, let’s examine how indicator columns shown in <a href="#tbl-indicators" class="quarto-xref">Table&nbsp;<span>6.1</span></a> affect an example data analysis. Suppose that we are modeling a numeric outcome using a linear regression model (discussed in <span class="quarto-unresolved-ref">?sec-reg-linear</span>) of the form:</p>
<p><span id="eq-linear-reg-again"><span class="math display">\[
y_i = \beta_0 + \beta_1x_{i1} + \ldots + \beta_4x_{i4} + \epsilon_i
\tag{6.1}\]</span></span></p>
<p>where the <span class="math inline">\(\beta\)</span> values are the parameters to be estimated and, in this application, the <span class="math inline">\(x_{ij}\)</span> are the indicator columns shown in <a href="#tbl-indicators" class="quarto-xref">Table&nbsp;<span>6.1</span></a>. The intercept term (<span class="math inline">\(\beta_0\)</span>) corresponds to a column of all ones. It is almost always the case that we include the intercept term in the model.</p>
<p><a href="#tbl-ref-cell-effects" class="quarto-xref">Table&nbsp;<span>6.2</span></a> shows the encoding in <a href="#tbl-indicators" class="quarto-xref">Table&nbsp;<span>6.1</span></a> and adds columns for a numeric outcome and the intercept term. The outcome column shows the average daily rate (in €). Using a standard estimation procedure (called ordinary least squares), the bottom row of <a href="#tbl-ref-cell-effects" class="quarto-xref">Table&nbsp;<span>6.2</span></a> shows the 4 parameter estimates. Since all of the indicators for the contract customer row are zero, the intercept column estimates the mean value for that level (<span class="math inline">\(\widehat{\beta}_0\)</span> = 73). The variable <span class="math inline">\(x_{i1}\)</span> only has an indicator for the “group” customers. Hence, its estimate corresponds to the difference in the average group outcome values (63.8) minus the effect of the reference cell: 73 - 63.8. From this, the resulting estimate (<span class="math inline">\(\widehat{\beta}_1\)</span> = -9.23) is the effect of the group customers above and beyond the impact of the contract customers. The parameter estimates for the other possible values follow analogous interpretations.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ref-cell-effects" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-ref-cell-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="hvsfpkylsn" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hvsfpkylsn table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hvsfpkylsn thead, #hvsfpkylsn tbody, #hvsfpkylsn tfoot, #hvsfpkylsn tr, #hvsfpkylsn td, #hvsfpkylsn th {
  border-style: none;
}

#hvsfpkylsn p {
  margin: 0;
  padding: 0;
}

#hvsfpkylsn .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: 66%;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hvsfpkylsn .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hvsfpkylsn .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hvsfpkylsn .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hvsfpkylsn .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hvsfpkylsn .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hvsfpkylsn .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hvsfpkylsn .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hvsfpkylsn .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hvsfpkylsn .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hvsfpkylsn .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hvsfpkylsn .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hvsfpkylsn .gt_spanner_row {
  border-bottom-style: hidden;
}

#hvsfpkylsn .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hvsfpkylsn .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hvsfpkylsn .gt_from_md > :first-child {
  margin-top: 0;
}

#hvsfpkylsn .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hvsfpkylsn .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hvsfpkylsn .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hvsfpkylsn .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hvsfpkylsn .gt_row_group_first td {
  border-top-width: 2px;
}

#hvsfpkylsn .gt_row_group_first th {
  border-top-width: 2px;
}

#hvsfpkylsn .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hvsfpkylsn .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hvsfpkylsn .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hvsfpkylsn .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hvsfpkylsn .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hvsfpkylsn .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hvsfpkylsn .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hvsfpkylsn .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hvsfpkylsn .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hvsfpkylsn .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hvsfpkylsn .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hvsfpkylsn .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hvsfpkylsn .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hvsfpkylsn .gt_left {
  text-align: left;
}

#hvsfpkylsn .gt_center {
  text-align: center;
}

#hvsfpkylsn .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hvsfpkylsn .gt_font_normal {
  font-weight: normal;
}

#hvsfpkylsn .gt_font_bold {
  font-weight: bold;
}

#hvsfpkylsn .gt_font_italic {
  font-style: italic;
}

#hvsfpkylsn .gt_super {
  font-size: 65%;
}

#hvsfpkylsn .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hvsfpkylsn .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hvsfpkylsn .gt_indent_1 {
  text-indent: 5px;
}

#hvsfpkylsn .gt_indent_2 {
  text-indent: 10px;
}

#hvsfpkylsn .gt_indent_3 {
  text-indent: 15px;
}

#hvsfpkylsn .gt_indent_4 {
  text-indent: 20px;
}

#hvsfpkylsn .gt_indent_5 {
  text-indent: 25px;
}

#hvsfpkylsn .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#hvsfpkylsn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="info" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"></th>
<th rowspan="2" id="ADR" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">ADR</th>
<th colspan="4" id="Model Terms" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
Model Terms
</div></th>
</tr>
<tr class="gt_col_headings even">
<th id="a(Intercept)" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">(Intercept)</th>
<th id="group" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">group</th>
<th id="transient" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">transient</th>
<th id="transient_party" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">transient_party</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="info">contract</td>
<td class="gt_row gt_right" headers="ADR">73.0</td>
<td class="gt_row gt_right" headers="(Intercept)">1</td>
<td class="gt_row gt_right" headers="group">0</td>
<td class="gt_row gt_right" headers="transient">0</td>
<td class="gt_row gt_right" headers="transient_party">0</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="info">group</td>
<td class="gt_row gt_right" headers="ADR">63.8</td>
<td class="gt_row gt_right" headers="(Intercept)">1</td>
<td class="gt_row gt_right" headers="group">1</td>
<td class="gt_row gt_right" headers="transient">0</td>
<td class="gt_row gt_right" headers="transient_party">0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="info">transient</td>
<td class="gt_row gt_right" headers="ADR">94.6</td>
<td class="gt_row gt_right" headers="(Intercept)">1</td>
<td class="gt_row gt_right" headers="group">0</td>
<td class="gt_row gt_right" headers="transient">1</td>
<td class="gt_row gt_right" headers="transient_party">0</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="info">transient party</td>
<td class="gt_row gt_right" headers="ADR">76.4</td>
<td class="gt_row gt_right" headers="(Intercept)">1</td>
<td class="gt_row gt_right" headers="group">0</td>
<td class="gt_row gt_right" headers="transient">0</td>
<td class="gt_row gt_right" headers="transient_party">1</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="info" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">estimate (€):</td>
<td class="gt_row gt_right" headers="ADR" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000"><br>
</td>
<td class="gt_row gt_right" headers="(Intercept)" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">73.0</td>
<td class="gt_row gt_right" headers="group" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">-9.2</td>
<td class="gt_row gt_right" headers="transient" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">21.6</td>
<td class="gt_row gt_right" headers="transient_party" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">3.4</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-ref-cell-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: An example of linear regression parameter estimates corresponding to a reference cell parameterization.
</figcaption>
</figure>
</div>
</div>
<p>Another popular method for making indicator variables is called <strong>one-hot encoding</strong> (also known as a cell means encoding). This technique, shown in <a href="#tbl-one-hot" class="quarto-xref">Table&nbsp;<span>6.3</span></a>, makes indicators for all possible levels of the predictor and does <em>not</em> show an intercept column (for reasons described shortly). In this model parameterization, indicators are specific to each value in the data, and the linear regression estimates are the average response values for each customer type.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-one-hot" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-one-hot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="rclvisvkig" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#rclvisvkig table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#rclvisvkig thead, #rclvisvkig tbody, #rclvisvkig tfoot, #rclvisvkig tr, #rclvisvkig td, #rclvisvkig th {
  border-style: none;
}

#rclvisvkig p {
  margin: 0;
  padding: 0;
}

#rclvisvkig .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: 69%;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#rclvisvkig .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#rclvisvkig .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rclvisvkig .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rclvisvkig .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rclvisvkig .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rclvisvkig .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rclvisvkig .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rclvisvkig .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rclvisvkig .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rclvisvkig .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rclvisvkig .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rclvisvkig .gt_spanner_row {
  border-bottom-style: hidden;
}

#rclvisvkig .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#rclvisvkig .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rclvisvkig .gt_from_md > :first-child {
  margin-top: 0;
}

#rclvisvkig .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rclvisvkig .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rclvisvkig .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#rclvisvkig .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#rclvisvkig .gt_row_group_first td {
  border-top-width: 2px;
}

#rclvisvkig .gt_row_group_first th {
  border-top-width: 2px;
}

#rclvisvkig .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rclvisvkig .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#rclvisvkig .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#rclvisvkig .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rclvisvkig .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rclvisvkig .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rclvisvkig .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#rclvisvkig .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rclvisvkig .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rclvisvkig .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rclvisvkig .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rclvisvkig .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rclvisvkig .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rclvisvkig .gt_left {
  text-align: left;
}

#rclvisvkig .gt_center {
  text-align: center;
}

#rclvisvkig .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rclvisvkig .gt_font_normal {
  font-weight: normal;
}

#rclvisvkig .gt_font_bold {
  font-weight: bold;
}

#rclvisvkig .gt_font_italic {
  font-style: italic;
}

#rclvisvkig .gt_super {
  font-size: 65%;
}

#rclvisvkig .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#rclvisvkig .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#rclvisvkig .gt_indent_1 {
  text-indent: 5px;
}

#rclvisvkig .gt_indent_2 {
  text-indent: 10px;
}

#rclvisvkig .gt_indent_3 {
  text-indent: 15px;
}

#rclvisvkig .gt_indent_4 {
  text-indent: 20px;
}

#rclvisvkig .gt_indent_5 {
  text-indent: 25px;
}

#rclvisvkig .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#rclvisvkig div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="info" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col"></th>
<th rowspan="2" id="ADR" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">ADR</th>
<th colspan="4" id="Model Terms" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
Model Terms
</div></th>
</tr>
<tr class="gt_col_headings even">
<th id="contract" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">contract</th>
<th id="group" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">group</th>
<th id="transient" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">transient</th>
<th id="transient_party" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">transient_party</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="info">contract</td>
<td class="gt_row gt_right" headers="ADR">73.0</td>
<td class="gt_row gt_right" headers="contract">1</td>
<td class="gt_row gt_right" headers="group">0</td>
<td class="gt_row gt_right" headers="transient">0</td>
<td class="gt_row gt_right" headers="transient_party">0</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="info">group</td>
<td class="gt_row gt_right" headers="ADR">63.8</td>
<td class="gt_row gt_right" headers="contract">0</td>
<td class="gt_row gt_right" headers="group">1</td>
<td class="gt_row gt_right" headers="transient">0</td>
<td class="gt_row gt_right" headers="transient_party">0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="info">transient</td>
<td class="gt_row gt_right" headers="ADR">94.6</td>
<td class="gt_row gt_right" headers="contract">0</td>
<td class="gt_row gt_right" headers="group">0</td>
<td class="gt_row gt_right" headers="transient">1</td>
<td class="gt_row gt_right" headers="transient_party">0</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="info">transient party</td>
<td class="gt_row gt_right" headers="ADR">76.4</td>
<td class="gt_row gt_right" headers="contract">0</td>
<td class="gt_row gt_right" headers="group">0</td>
<td class="gt_row gt_right" headers="transient">0</td>
<td class="gt_row gt_right" headers="transient_party">1</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="info" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">estimate (€):</td>
<td class="gt_row gt_right" headers="ADR" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000"><br>
</td>
<td class="gt_row gt_right" headers="contract" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">73.0</td>
<td class="gt_row gt_right" headers="group" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">63.8</td>
<td class="gt_row gt_right" headers="transient" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">94.6</td>
<td class="gt_row gt_right" headers="transient_party" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000">76.4</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-one-hot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: One-hot encoded indicator variables from a categorical column of data.
</figcaption>
</figure>
</div>
</div>
<p>One-hot encodings are often used in nonlinear models, especially in neural networks and tree-based models. Indicators are not generally required for the latter but can be used<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<p>One issue with creating indicator variables from categorical predictors is the potential for <strong>linear dependencies</strong>. This occurs when two or more sets of predictors have a mathematically linear relationship with one another. For example, suppose that each agent only worked with a single customer type. If we were to create indicator variables for the agent names and the customer type, there would be a redundancy: if we know the agent, we know the customer type. Mathematically, the row-wise sum of the agent name indicators would equal the row-wise sum of the position indicators. For some types of predictive models, including linear or logistic regression, the linear dependencies would cause the mathematical estimation of the model parameters to fail.</p>
<p>An example of this is the one-hot encoding method shown in <a href="#tbl-one-hot" class="quarto-xref">Table&nbsp;<span>6.3</span></a>. If we were to include an intercept term with a one-hot encoding, the row-wise sum of the indicator columns equals the intercept column. The implication is that one of the model terms is not “estimable.” For this reason, this encoding method is mainly used with models that do not use specific linear algebra operations (e.g., matrix inversion) to estimate parameters. Some tools can identify linear combinations <span class="citation" data-cites="estimable">(<a href="#ref-estimable" role="doc-biblioref">Elswick et al. 1991</a>)</span>, and from this information, the smallest possible set of columns can be found to delete and thereby eliminate the linear dependencies.</p>
<p>Note that linear dependencies are exact linear relationships between predictors. There are other circumstances where two or more predictors are highly correlated but not perfectly related. This situation, called <strong>multicollinearity</strong>, is discussed throughout the book but mostly in <span class="quarto-unresolved-ref">?sec-colinearity</span>. Multicollinearity can be a problem for many models and needs to be resolved prior to modeling.</p>
<p>In addition to reference cell and one-hot encodings, there are various tools for creating indicator columns. Some, called <em>contrast methods</em>, are associated with more niche strategies, and many produce fractional values instead of binary indicators. For example, Helmert contrasts <span class="citation" data-cites="ruberg">(<a href="#ref-ruberg" role="doc-biblioref">Ruberg 1989</a>)</span> are configured so that each category is compared to the average of the preceding categories. No encoding method is uniformly better than the others; the choice is often driven by how the user will interpret the parameter estimates.</p>
<p>The situation becomes slightly more complex when a model contains multiple categorical predictors. The reference value combines levels across predictors for reference value parameterizations. For example, if a model included the customer’s country of residence, the reference would include that factor. Suppose Canadians were the reference nationality. Then the overall reference cell would be Canadian contract customers.</p>
<p>Note that these encoding techniques are basically look-up tables that map individual categories known in the training set to specific numeric values. As discussed in the next section, mapping categories can be problematic when novel values are seen in new data (such as the test set).</p>
</section>
<section id="sec-novel-categories" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-novel-categories"><span class="header-section-number">6.3</span> Novel Categories</h2>
<p>When creating indicator variables, there is the assumption that the categories in the training data reflect all possible categories. This may not be the case. For example, the agents observed in our data are not the only agents that will be booking rooms in the future. After we create a model with a specific set of agents, what happens when we predict future data that involves new agents?</p>
<p>One approach we could take is to prospectively create a new value for the predictor (let’s give it a value of <code>"new"</code>). When a future sample has an agent that was not in the original data, we could assign this sample to the general category so that the model can anticipate this new level. In general, this won’t help since the model estimation process will never have any “new” values on hand when the model is fit. For some models, this is innocuous and has no real harm (but offers no benefit either).</p>
<p>Let’s revisit linear regression results from the reference cell parameterization again. Suppose there is a new customer type of “influencer.” Our reference cell encoding method could add an indicator column for that customer type, but since no influencers currently exist in the training data, it will be a column filled with zeros. We can call this a <strong>zero-variance predictor</strong> since it has a single unique value. It is entirely non-informative. For linear regression, this column of zeros creates a linear dependency with the intercept column because all rows have the same numeric value. Most regression software would detect zero-variance columns and remove them before the model is fit.</p>
<p>Since there would be no influencer column in the data, all of the indicator columns would be zero when an influencer was observed in new data being predicted. However, from <a href="#tbl-ref-cell-effects" class="quarto-xref">Table&nbsp;<span>6.2</span></a> we know that such a pattern would map to the reference level (which is the <code>"contract"</code> customer in our data). The new levels would be mapped to the reference level for this parameterization. This would occur more by happenstance and would not be a deliberate strategy.</p>
<p>Traditional indicator encoding methods should be avoided if new predictor categories are anticipated. Instead, the techniques used in the next section (effect encodings or feature hashing) will likely be more effective at dealing with this situation.</p>
</section>
<section id="sec-high-cardinality" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-high-cardinality"><span class="header-section-number">6.4</span> Predictors with Many Values</h2>
<p>Some predictors have high cardinality; they can take many possible values relative to the number of data points. For example, in the entirety of the hotel rate data, there are 122 unique agents (see <a href="#fig-agents" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>). Should we create so many indicator variables for this predictor? In the data, 49 agents had fewer than six bookings. This means there will be many sparse columns with almost all zero entries. Additionally, 71 of the agents have no data in the training set; they only occur in the test set. Their indicator columns would contain all zeros.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-agents" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-agents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/fig-agents-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-agents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: The frequency distribution of agents in the training set.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This section will consider several methods for effectively representing high cardinality predictors. The first two techniques are unsupervised (i.e., they do not use the outcome), while the others are supervised. <span class="citation" data-cites="Cerda2022">Cerda and Varoquaux (<a href="#ref-Cerda2022" role="doc-biblioref">2022</a>)</span> surveys different methods for dealing with these types of predictors.</p>
<section id="sec-other" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="sec-other"><span class="header-section-number">6.4.1</span> “Othering”</h3>
<p>It is possible to isolate infrequently occurring categories into a new “other” category. For example, there are 49 agents with fewer bookings than 0.05% of the training set. It may make sense to group these agents into their own categories as long as the predictive ability of the variable is maintained. There is no magic number for the training set frequency cutoff that decides which categories to pool. This pre-processing value requires optimization since each data set will have its own nuances with infrequent categories.</p>
</section>
<section id="sec-feature-hashing" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="sec-feature-hashing"><span class="header-section-number">6.4.2</span> Feature Hashing</h3>
<p>Feature hashing <span class="citation" data-cites="weinberger2009feature">(<a href="#ref-weinberger2009feature" role="doc-biblioref">Weinberger et al. 2009</a>)</span> is a technique where the user specifies how many indicator columns should be used to represent the data. Using cryptographic principles, an algorithm assigns each row to an indicator column. This assignment only uses the value of the category in the calculations and, unlike the traditional methods discussed in <a href="#sec-indicators" class="quarto-xref"><span>Section 6.2</span></a>, does not require a dictionary that maps pre-defined categories to indicator columns.</p>
<p>Suppose our agent column had a value of <code>"nobody owens"</code>. The algorithm translates this value to a fixed-length string using a <em>hash function</em>. Hash functions are designed to be non-random and, effectively, irreversible. Once the original value is converted to the <em>hash value</em>, it is very difficult to reverse engineer. Also, the frequency distributions of the hash values are designed to appear uniform in distribution, as seen below.</p>
<p>The hashed value of the predictor’s level can be converted to an integer, and, using modular arithmetic, the integer is mapped to a feature column. Suppose that we create 256 hashing features and <code>nobody owens</code> maps to an integer of 123,456. To assign this agent to one of 256 feature columns, we compute <code>123456 mod 256</code> = 64. For this row of data, we put a value of one in column 64.</p>
<p>Presumably, the number of possible categories is larger than the number of indicator columns we request. This means multiple predictor values will map to the same feature column. In cryptography, this is called a <em>collision</em>, the same as <em>aliasing</em> in statistical experimental design <span class="citation" data-cites="BHH">(<a href="#ref-BHH" role="doc-biblioref">Box, Hunter, and Hunter 1978</a>)</span>. There is a trade-off between the number of feature columns and the number of collisions. As the number of columns increases, the probability of collisions decreases. However, the time required to train a model increases as the number of columns increases. Also, it is entirely possible that there are predictor columns where <em>no</em> corresponding categories, yielding all zeros.</p>
<p>To reduce collisions, the hashing function can produce integers that can be both positive and negative. When assigning the integer to a feature column, we can assign a value of -1 when the hashed integer value is negative. In this way, columns can have values of -1, 0, or 1. This means fewer collisions.</p>
<p><a href="#tbl-feature-hash" class="quarto-xref">Table&nbsp;<span>6.4</span></a> shows the results for several agents<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> when ten signed feature hash columns are requested. The last row of the table shows the rate of non-zero values in each column. The average density is close to 10%, demonstrating that the hash function produces frequencies that emulate a uniform distribution.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-feature-hash" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-feature-hash-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="jbsdzuyukc" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#jbsdzuyukc table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#jbsdzuyukc thead, #jbsdzuyukc tbody, #jbsdzuyukc tfoot, #jbsdzuyukc tr, #jbsdzuyukc td, #jbsdzuyukc th {
  border-style: none;
}

#jbsdzuyukc p {
  margin: 0;
  padding: 0;
}

#jbsdzuyukc .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: 70%;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jbsdzuyukc .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#jbsdzuyukc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jbsdzuyukc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jbsdzuyukc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jbsdzuyukc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jbsdzuyukc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jbsdzuyukc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jbsdzuyukc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jbsdzuyukc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jbsdzuyukc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jbsdzuyukc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jbsdzuyukc .gt_spanner_row {
  border-bottom-style: hidden;
}

#jbsdzuyukc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#jbsdzuyukc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jbsdzuyukc .gt_from_md > :first-child {
  margin-top: 0;
}

#jbsdzuyukc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jbsdzuyukc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jbsdzuyukc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#jbsdzuyukc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#jbsdzuyukc .gt_row_group_first td {
  border-top-width: 2px;
}

#jbsdzuyukc .gt_row_group_first th {
  border-top-width: 2px;
}

#jbsdzuyukc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jbsdzuyukc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#jbsdzuyukc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#jbsdzuyukc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jbsdzuyukc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jbsdzuyukc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jbsdzuyukc .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#jbsdzuyukc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jbsdzuyukc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jbsdzuyukc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jbsdzuyukc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jbsdzuyukc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jbsdzuyukc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jbsdzuyukc .gt_left {
  text-align: left;
}

#jbsdzuyukc .gt_center {
  text-align: center;
}

#jbsdzuyukc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jbsdzuyukc .gt_font_normal {
  font-weight: normal;
}

#jbsdzuyukc .gt_font_bold {
  font-weight: bold;
}

#jbsdzuyukc .gt_font_italic {
  font-style: italic;
}

#jbsdzuyukc .gt_super {
  font-size: 65%;
}

#jbsdzuyukc .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#jbsdzuyukc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#jbsdzuyukc .gt_indent_1 {
  text-indent: 5px;
}

#jbsdzuyukc .gt_indent_2 {
  text-indent: 10px;
}

#jbsdzuyukc .gt_indent_3 {
  text-indent: 15px;
}

#jbsdzuyukc .gt_indent_4 {
  text-indent: 20px;
}

#jbsdzuyukc .gt_indent_5 {
  text-indent: 25px;
}

#jbsdzuyukc .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#jbsdzuyukc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="Agent" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Agent</th>
<th colspan="10" id="Features from Hashing" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><div class="gt_column_spanner">
Features from Hashing
</div></th>
</tr>
<tr class="gt_col_headings even">
<th id="a01" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">01</th>
<th id="a02" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">02</th>
<th id="a03" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">03</th>
<th id="a04" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">04</th>
<th id="a05" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">05</th>
<th id="a06" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">06</th>
<th id="a07" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">07</th>
<th id="a08" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">08</th>
<th id="a09" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">09</th>
<th id="a10" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">10</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="Agent">Aaron Marquez</td>
<td class="gt_row gt_right" headers="01">0</td>
<td class="gt_row gt_right" headers="02">0</td>
<td class="gt_row gt_right" headers="03">0</td>
<td class="gt_row gt_right" headers="04">0</td>
<td class="gt_row gt_right" headers="05">0</td>
<td class="gt_row gt_right" headers="06">0</td>
<td class="gt_row gt_right" headers="07">0</td>
<td class="gt_row gt_right" headers="08">0</td>
<td class="gt_row gt_right" headers="09">0</td>
<td class="gt_row gt_right" headers="10">-1</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="Agent">Alexander Drake</td>
<td class="gt_row gt_right" headers="01">0</td>
<td class="gt_row gt_right" headers="02">0</td>
<td class="gt_row gt_right" headers="03">0</td>
<td class="gt_row gt_right" headers="04">0</td>
<td class="gt_row gt_right" headers="05">0</td>
<td class="gt_row gt_right" headers="06">0</td>
<td class="gt_row gt_right" headers="07">0</td>
<td class="gt_row gt_right" headers="08">-1</td>
<td class="gt_row gt_right" headers="09">0</td>
<td class="gt_row gt_right" headers="10">0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="Agent">Allen Her</td>
<td class="gt_row gt_right" headers="01">0</td>
<td class="gt_row gt_right" headers="02">0</td>
<td class="gt_row gt_right" headers="03">0</td>
<td class="gt_row gt_right" headers="04">0</td>
<td class="gt_row gt_right" headers="05">0</td>
<td class="gt_row gt_right" headers="06">0</td>
<td class="gt_row gt_right" headers="07">0</td>
<td class="gt_row gt_right" headers="08">0</td>
<td class="gt_row gt_right" headers="09">-1</td>
<td class="gt_row gt_right" headers="10">0</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="Agent">Anas El Bashir</td>
<td class="gt_row gt_right" headers="01">0</td>
<td class="gt_row gt_right" headers="02">0</td>
<td class="gt_row gt_right" headers="03">0</td>
<td class="gt_row gt_right" headers="04">0</td>
<td class="gt_row gt_right" headers="05">-1</td>
<td class="gt_row gt_right" headers="06">0</td>
<td class="gt_row gt_right" headers="07">0</td>
<td class="gt_row gt_right" headers="08">0</td>
<td class="gt_row gt_right" headers="09">0</td>
<td class="gt_row gt_right" headers="10">0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="Agent">:</td>
<td class="gt_row gt_right" headers="01">:</td>
<td class="gt_row gt_right" headers="02">:</td>
<td class="gt_row gt_right" headers="03">:</td>
<td class="gt_row gt_right" headers="04">:</td>
<td class="gt_row gt_right" headers="05">:</td>
<td class="gt_row gt_right" headers="06">:</td>
<td class="gt_row gt_right" headers="07">:</td>
<td class="gt_row gt_right" headers="08">:</td>
<td class="gt_row gt_right" headers="09">:</td>
<td class="gt_row gt_right" headers="10">:</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="Agent">Ya Eesh El Sadiq</td>
<td class="gt_row gt_right" headers="01">0</td>
<td class="gt_row gt_right" headers="02">-1</td>
<td class="gt_row gt_right" headers="03">0</td>
<td class="gt_row gt_right" headers="04">0</td>
<td class="gt_row gt_right" headers="05">0</td>
<td class="gt_row gt_right" headers="06">0</td>
<td class="gt_row gt_right" headers="07">0</td>
<td class="gt_row gt_right" headers="08">0</td>
<td class="gt_row gt_right" headers="09">0</td>
<td class="gt_row gt_right" headers="10">0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="Agent">Yoonus Al Sultana</td>
<td class="gt_row gt_right" headers="01">0</td>
<td class="gt_row gt_right" headers="02">0</td>
<td class="gt_row gt_right" headers="03">0</td>
<td class="gt_row gt_right" headers="04">0</td>
<td class="gt_row gt_right" headers="05">1</td>
<td class="gt_row gt_right" headers="06">0</td>
<td class="gt_row gt_right" headers="07">0</td>
<td class="gt_row gt_right" headers="08">0</td>
<td class="gt_row gt_right" headers="09">0</td>
<td class="gt_row gt_right" headers="10">0</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="Agent">Youjia Tsuchiya</td>
<td class="gt_row gt_right" headers="01">1</td>
<td class="gt_row gt_right" headers="02">0</td>
<td class="gt_row gt_right" headers="03">0</td>
<td class="gt_row gt_right" headers="04">0</td>
<td class="gt_row gt_right" headers="05">0</td>
<td class="gt_row gt_right" headers="06">0</td>
<td class="gt_row gt_right" headers="07">0</td>
<td class="gt_row gt_right" headers="08">0</td>
<td class="gt_row gt_right" headers="09">0</td>
<td class="gt_row gt_right" headers="10">0</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="Agent">Zachary Leedholm</td>
<td class="gt_row gt_right" headers="01">0</td>
<td class="gt_row gt_right" headers="02">-1</td>
<td class="gt_row gt_right" headers="03">0</td>
<td class="gt_row gt_right" headers="04">0</td>
<td class="gt_row gt_right" headers="05">0</td>
<td class="gt_row gt_right" headers="06">0</td>
<td class="gt_row gt_right" headers="07">0</td>
<td class="gt_row gt_right" headers="08">0</td>
<td class="gt_row gt_right" headers="09">0</td>
<td class="gt_row gt_right" headers="10">0</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="Agent" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">Density (%)</td>
<td class="gt_row gt_right" headers="01" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">10.7</td>
<td class="gt_row gt_right" headers="02" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">13.1</td>
<td class="gt_row gt_right" headers="03" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">7.4</td>
<td class="gt_row gt_right" headers="04" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">13.1</td>
<td class="gt_row gt_right" headers="05" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">7.4</td>
<td class="gt_row gt_right" headers="06" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">6.6</td>
<td class="gt_row gt_right" headers="07" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">9.8</td>
<td class="gt_row gt_right" headers="08" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">10.7</td>
<td class="gt_row gt_right" headers="09" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">9.8</td>
<td class="gt_row gt_right" headers="10" style="border-top-width: 2px; border-top-style: solid; border-top-color: #000000; border-bottom-width: 2px; border-bottom-style: solid; border-bottom-color: #000000; background-color: #FFFFFF">11.5</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-feature-hash-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.4: Signed indicators for agent via feature hashing.
</figcaption>
</figure>
</div>
</div>
<p>The main downside of this method is that the use of hash values makes it impossible to explain the model. If the tenth feature column is critical, we can’t explain why this is the case for new data (since the hash function is practically non-reversible and may include collisions). This may be fine if the primary objective is prediction rather than interpretation. When the goal is to optimize predictive performance, then the number of hashing columns to use can be included as a tuning parameter. The model tuning process can then determine an optimal value of the number of hashing columns.</p>
<p>One unanticipated side effect of using feature hashing is that it <em>might</em> remove linear dependencies with other columns. This is because hashing distributes the predictor levels to hashing columns roughly uniformly. There is a high probability that this eliminates any existing relationship between other predictor values.</p>
</section>
<section id="sec-effect-encodings" class="level3" data-number="6.4.3">
<h3 data-number="6.4.3" class="anchored" data-anchor-id="sec-effect-encodings"><span class="header-section-number">6.4.3</span> Effect Encodings</h3>
<p>We can also use a different supervised tool called <em>effect encoding</em><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> <span class="citation" data-cites="MicciBarreca2001 pargent2022regularized">(<a href="#ref-MicciBarreca2001" role="doc-biblioref">Micci-Barreca 2001</a>; <a href="#ref-pargent2022regularized" role="doc-biblioref">Pargent et al. 2022</a>)</span>. Recall the discussion of one-hot encodings for indicator variables. <a href="#tbl-one-hot" class="quarto-xref">Table&nbsp;<span>6.3</span></a> showed that the model terms for such an encoding estimate the cell means for each category (when the outcome is numeric). For example, the effect on the outcome for contract customers in that table was 73€.</p>
<p>Effect encodings use a simple, separate model to estimate the effect of each predictor category on the outcome and then use that value in place of the original data. For the example in <a href="#tbl-one-hot" class="quarto-xref">Table&nbsp;<span>6.3</span></a>, the rows corresponding to the group customers would be replaced with 63.8, transient customers with 94.6, and so on. Instead of making multiple binary columns out of the categorical predictor, a single numeric column would take its place.</p>
<p>This may seem somewhat problematic though; we are using the training data to estimate <strong>the effect of a predictor</strong>, putting the resulting effects back into the data, and using our primary model to (re)estimate the effect of the predictor. Since the same data are used, is this a circular argument? Also, there should be a worry about data quality. As previously mentioned, the number of bookings per agent can vary greatly. For example:</p>
<ul>
<li><p>Agent Chelsea Wilson had a single booking with an associated ADR of 193.6€. Using this single data point as the effect estimate is unsatisfactory since we suspect that the estimated ADR would not stay the same if the number of total bookings were larger<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>.</p></li>
<li><p>Agent Alexander Drake had 967 bookings with a simple mean ADR estimate of 120.3€. We would judge the quality of this agent’s data to be better than cases with a handful of bookings.</p></li>
</ul>
<p>How well can we estimate an effect if there are only one or two bookings for an agent in the data set?</p>
<p>Both of these concerns can be addressed by <em>how</em> we estimate the effect of the predictor. Recall that <a href="#tbl-one-hot" class="quarto-xref">Table&nbsp;<span>6.3</span></a> showed how simple linear regression was used to calculate the mean for each customer type. The way that the indicator variables impact the parameter estimates is such that the rows for each customer type are the only data used to estimate that customer type’s effect. For example, the contract data do not directly affect the parameter estimate for the transient customers, and so on. This is often called a <em>no pooling</em> method of estimating parameters. In this context, “pooling” means combining data across multiple categories to estimate parameters.</p>
<p>We could compute the naive ADR estimate using sample means and produce a similar table. However, we can create better mean estimates for each agent by considering the data from <em>all</em> agents using a technique called <em>partial pooling</em> <span class="citation" data-cites="gelman1995bayesian BayesRules">(<a href="#ref-gelman1995bayesian" role="doc-biblioref">Gelman et al. 2013</a>; <a href="#ref-BayesRules" role="doc-biblioref">Johnson, Ott, and Dogucu 2022, chap. 15</a>)</span>.</p>
<div class="mathy-box">
<p>In the following two sub-sections, we’ll describe this technique in detail for cases where the outcome is a numeric value assumed to be normally distributed or or non-Gaussian. These sections will rely more on probability theory and statistical details than most others.</p>
</div>
<section id="numeric-outcomes" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="numeric-outcomes">Numeric outcomes</h4>
<p>For our ADR analysis, the outcome is a quantitative value. A linear regression model (see <span class="quarto-unresolved-ref">?sec-linear-regression</span>) is the most commonly used approach to model this type of outcome. Linear regression models the outcome as a function of a slope and intercept model. For our example, where we only consider estimating the effect of the agents using indicator columns, the model is:</p>
<p><span class="math display">\[
y_{ij} =\beta_0 + \beta_1x_{i1} + \ldots + \beta_{121}x_{i 121} + \epsilon_{ij} = \mu_i  + \epsilon_{ij}
\]</span></p>
<p>where <span class="math inline">\(y_{ij}\)</span> is the outcome (in this case, the ADR of booking <span class="math inline">\(i\)</span> by agent <span class="math inline">\(j\)</span>), <span class="math inline">\(x_{ij}\)</span> is an indicator for reservation <span class="math inline">\(i\)</span> from agent <span class="math inline">\(j\)</span>, <span class="math inline">\(\beta_0\)</span> is the estimated outcome of the reference cell, and we assume <span class="math inline">\(\epsilon_i \sim N(0, \sigma^2_\epsilon)\)</span>. This leads to the assumption that <span class="math inline">\(y_{ij} \sim N(\mu_i, \sigma^2_\epsilon)\)</span>. The <span class="math inline">\(\hat{\beta}_{j}\)</span> parameters are the effect of the agents above and beyond the reference cell effect. The index <span class="math inline">\(j\)</span> is from 1 to 121 since there were 122 agents in the training set with at least one booking.</p>
<p>Again, this approach is called <em>no pooling</em> since it only uses each agent’s data to estimate their effect. It treats the agent as a known set of values and cannot generalize to agents outside of those in the training set<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>.</p>
<p><em>Partial pooling</em> takes the viewpoint that the agents in the training set are a sample of a <em>population</em> of agents. From this, we might posit a probability distribution should be assigned to the agent-to-agent effects. Since the range of the <span class="math inline">\(\beta\)</span> parameters is the real line, we might propose a <em>random intercept model</em>:</p>
<p><span id="eq-effect-random-int"><span class="math display">\[
y_{ij} = { \color{darkseagreen} \underbrace{\color{black} (\beta_0 + \beta_{0j})}_{\text{intercept(s)}} }  + \epsilon_{ij} = \mu_j + \epsilon_{ij}
\tag{6.2}\]</span></span></p>
<p>where the <span class="math inline">\(\beta_{0j}\)</span> are per-agent differences from the population effect (<span class="math inline">\(\beta_{0}\)</span>) (<span class="math inline">\(j = 1 \ldots 122\)</span> this time). Note that the model has no <span class="math inline">\(x_{ij}\)</span> terms. This is simply a notation difference between the models since most methods that estimate this model do not treat that variable as a traditional regression covariate.</p>
<p>Several techniques can fit this model. For a <em>linear mixed model</em> approach to fitting a random intercept model <span class="citation" data-cites="demidenko2013mixed laird1982random">(<a href="#ref-laird1982random" role="doc-biblioref">Laird and Ware 1982</a>; <a href="#ref-demidenko2013mixed" role="doc-biblioref">Demidenko 2013</a>)</span>, we assume that the model parameters have normal distributions with <span class="math inline">\(\beta_{0} \sim N(\beta, \sigma^2)\)</span> and <span class="math inline">\(\beta_{0j} \sim N(0, \sigma_0^2)\)</span> and that residuals (<span class="math inline">\(\epsilon_{ij}\)</span>) follow a Gaussian distribution. When used in Bayesian analysis, such distributions on parameters are referred to as <em>prior distributions</em>. We’ll stick with this terminology for Bayesian and non-Bayesian techniques. There are many strategies for estimating this model type, including maximum likelihood, restricted maximum likelihood, or Bayesian methods. See <span class="citation" data-cites="stroup2012generalized">Stroup (<a href="#ref-stroup2012generalized" role="doc-biblioref">2012</a>)</span> or <span class="citation" data-cites="gelman1995bayesian">Gelman et al. (<a href="#ref-gelman1995bayesian" role="doc-biblioref">2013</a>)</span> for more specifics.</p>
<p>However, we might gain some intuition if we pause and consider a less complex version of this model. For simplicity, we’ll also make the completely unrealistic assumptions that all agents had the same number of bookings (<span class="math inline">\(n_j = n\)</span>) and that we know that <span class="math inline">\(\sigma^2_\epsilon = 1\)</span>. From this, we can also say that sample means of the outcome data for each category are also normal with <span class="math inline">\(\bar{y}_{j} \sim N(\mu_i, 1/n)\)</span>. These assumptions greatly simplify the math required to produce a formula for the estimates of the per-category means:</p>
<p><span id="eq-effect-posterior"><span class="math display">\[
\hat{y}_j = \mu_0 + (\bar{y}_j - \mu_0) \frac{\sigma^2_0}{\frac{1}{n} + \sigma^2_0}
\tag{6.3}\]</span></span></p>
<p>There are a few aspects of this equation<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> to note. First, the effect for a specific category is estimated by a combination of the sample mean for each category (<span class="math inline">\(\bar{y}_j\)</span>) as well as our prior mean (<span class="math inline">\(\mu_0\)</span>). The difference demonstrates the possible shrinkage towards the prior mean.</p>
<p>Also, the shrinkage coefficient depends on <span class="math inline">\(\sigma^2_0\)</span> and the amount of data in the category. Suppose we choose a non-informative prior by making it extremely wide<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> via <span class="math inline">\(\sigma^2_0 = 100\)</span>. No matter how much data are observed in the category, the fraction will be close to 1, and our partial pooling estimate is essentially <span class="math inline">\(\bar{y}_j\)</span>. If we had a highly opinionated prior<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>, <span class="math inline">\(\sigma^2_0 = 1\)</span>, the weighting factor becomes <span class="math inline">\(n / (n + 1)\)</span>. For <span class="math inline">\(n = 1\)</span>, the partial pooling estimate has an even share of the sample mean and the prior mean. The effect of the prior mean decreases as <span class="math inline">\(n\)</span> increases.</p>
<p>These example computations assumed that each category has the same number of rows in the training set (i.e., <span class="math inline">\(n_j = n\)</span>). In practice, this is unrealistic. However, the insights into how the sample size changes the amount of shrinkage demonstrate the previous idea of how “poor data” can affect the estimates with partial pooling.</p>
<p>While <a href="#eq-effect-posterior" class="quarto-xref">Equation&nbsp;<span>6.3</span></a> helps illustrate how partial pooling works, we should understand that the specific results hinge on knowing <span class="math inline">\(\sigma^2_\epsilon = 1\)</span>. We would seldom make such a critical assumption in practice.</p>
<p>We’ll use the non-Bayesian mixed model approach to estimate effects for our data since it is more computationally efficient. Using the training set data, maximum likelihood estimation produced <span class="math inline">\(\hat{\beta}_0\)</span> = 76.9. <a href="#fig-effect-encoding" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>(a) shows the distribution of the 122 random intercept estimates <span class="math inline">\(\hat{\beta}_{0j}\)</span>. The estimated standard deviation of this distribution was <span class="math inline">\(\hat{\sigma_0}\)</span> = 22.9€. Even though we assume that the prior distribution of the individual effects was symmetric, the histogram of the estimates shows a lack of symmetry. This may be due to a few outliers or indicate that our prior should not be symmetric.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-effect-encoding" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-effect-encoding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/fig-effect-encoding-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-effect-encoding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: The effect encoding results for the hotel rate data. Panel (a) shows the distribution of the estimated per-agent effects. Panel (b) compares the two estimation methods for all unique data patterns in the training set.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The benefit of using this model, called a hierarchical model, is that it views the per-agent effects as a collection of values from a distribution. The mathematical consequence of this formulation is that the resulting parameter estimates use the data from all agents to estimate each agent’s estimates (hence the use of the phrase “partial pooling”). The intuition for that statistical method applies here: the estimates for agents with “poor data quality” have their results shrunken towards the overall population mean across all agents. Agents with “better” data are shrunken less during estimation. What does “poor data quality” mean? It primarily means high variance, which is usually a function of sample size and some baseline, the irreducible noise level in the system.</p>
<p>Recall the previous discussion regarding agents Chelsea Wilson and Alexander Drake. Using the partial pooling approach:</p>
<ul>
<li><p>Agent Chelsea Wilson: partial pooling shrinks the single value (193.6€) back towards the estimated population mean (76.9€) to produce a more modest estimated effect of 95.3€. Because there is a single value for this agent, the prior distribution greatly influences the final estimate.</p></li>
<li><p>Agent Alexander Drake: partial pooling only slightly adjusts the original sample mean (120.3€) to the final estimate (120.1€) since there are more data available. The prior has almost no influence on this estimate since the agent had 967 bookings in the training set.</p></li>
</ul>
<p>The amount of shrinkage was driven mainly by the number of bookings per agent. <a href="#fig-effect-encoding" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>(b) shows the collection of effect estimates for each unique data pattern in the training set. The dotted line indicates the overall ADR sample mean, and the size of the points indicates the total number of bookings by an agent. The distribution of the shrunken effects (<em>y</em>-axis) is significantly attenuated compared to the no pooling effects estimates (<em>x</em>-axis). However, note that the points with large numbers of bookings line up along the diagonal green line (i.e., minimal shrinkage to the center); regardless of the value of their agent-specific ADR estimate (<span class="math inline">\(\bar{y}_j\)</span>).</p>
<p>To reiterate how these values are used for pre-processing this type of predictor, <a href="#tbl-effect-estimates" class="quarto-xref">Table&nbsp;<span>6.5</span></a> shows the linear mixed model analysis results. The numeric column is our primary model’s data for representing the agent names. This avoids creating a large number of indicator variables for this predictor.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-effect-estimates" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-effect-estimates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="bkhsaljxcb" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#bkhsaljxcb table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#bkhsaljxcb thead, #bkhsaljxcb tbody, #bkhsaljxcb tfoot, #bkhsaljxcb tr, #bkhsaljxcb td, #bkhsaljxcb th {
  border-style: none;
}

#bkhsaljxcb p {
  margin: 0;
  padding: 0;
}

#bkhsaljxcb .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: 40%;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#bkhsaljxcb .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#bkhsaljxcb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#bkhsaljxcb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#bkhsaljxcb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bkhsaljxcb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bkhsaljxcb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bkhsaljxcb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#bkhsaljxcb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#bkhsaljxcb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#bkhsaljxcb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#bkhsaljxcb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#bkhsaljxcb .gt_spanner_row {
  border-bottom-style: hidden;
}

#bkhsaljxcb .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#bkhsaljxcb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#bkhsaljxcb .gt_from_md > :first-child {
  margin-top: 0;
}

#bkhsaljxcb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#bkhsaljxcb .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#bkhsaljxcb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#bkhsaljxcb .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#bkhsaljxcb .gt_row_group_first td {
  border-top-width: 2px;
}

#bkhsaljxcb .gt_row_group_first th {
  border-top-width: 2px;
}

#bkhsaljxcb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bkhsaljxcb .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#bkhsaljxcb .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#bkhsaljxcb .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bkhsaljxcb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bkhsaljxcb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#bkhsaljxcb .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#bkhsaljxcb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#bkhsaljxcb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bkhsaljxcb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bkhsaljxcb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bkhsaljxcb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bkhsaljxcb .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#bkhsaljxcb .gt_left {
  text-align: left;
}

#bkhsaljxcb .gt_center {
  text-align: center;
}

#bkhsaljxcb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#bkhsaljxcb .gt_font_normal {
  font-weight: normal;
}

#bkhsaljxcb .gt_font_bold {
  font-weight: bold;
}

#bkhsaljxcb .gt_font_italic {
  font-style: italic;
}

#bkhsaljxcb .gt_super {
  font-size: 65%;
}

#bkhsaljxcb .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#bkhsaljxcb .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#bkhsaljxcb .gt_indent_1 {
  text-indent: 5px;
}

#bkhsaljxcb .gt_indent_2 {
  text-indent: 10px;
}

#bkhsaljxcb .gt_indent_3 {
  text-indent: 15px;
}

#bkhsaljxcb .gt_indent_4 {
  text-indent: 20px;
}

#bkhsaljxcb .gt_indent_5 {
  text-indent: 25px;
}

#bkhsaljxcb .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#bkhsaljxcb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="Agent" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Agent</th>
<th id="Effect-Estimate-(€)" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col">Effect Estimate (€)</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="Agent">Aaron Marquez</td>
<td class="gt_row gt_center" headers="Effect Estimate (€)">92.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="Agent">Alexander Drake</td>
<td class="gt_row gt_center" headers="Effect Estimate (€)">120.1</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="Agent">Allen Her</td>
<td class="gt_row gt_center" headers="Effect Estimate (€)">73.7</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="Agent">:</td>
<td class="gt_row gt_center" headers="Effect Estimate (€)">:</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="Agent">Yoonus Al Sultana</td>
<td class="gt_row gt_center" headers="Effect Estimate (€)">58.8</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="Agent">Youjia Tsuchiya</td>
<td class="gt_row gt_center" headers="Effect Estimate (€)">74.8</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="Agent">Zachary Leedholm</td>
<td class="gt_row gt_center" headers="Effect Estimate (€)">85.6</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-effect-estimates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.5: Examples of the numeric values that are used in place of each agent’s data when effect encodings are used.
</figcaption>
</figure>
</div>
</div>
<p>As an alternative to generalized linear mixed models to estimate the effects, a more general approach uses <em>Bayesian analysis</em> <span class="citation" data-cites="kruschke2014doing Rethinking">(<a href="#ref-kruschke2014doing" role="doc-biblioref">Kruschke 2014</a>; <a href="#ref-Rethinking" role="doc-biblioref">McElreath 2015</a>)</span>. Here, we give all of the model parameters prior probability distributions, which reflect our prior knowledge of the parameters’ shape and range. “Priors” can be pretty vague or highly opinionated, depending on what we feel we know about the situation<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>. For example, to continue with the random intercept formulation, we might specify the following:</p>
<p><span class="math display">\[\begin{align}
\beta_0 &amp;\sim N(0, \sigma_0^2) \notag \\
\beta_{0j} &amp;\sim t(2) \notag \\
\sigma_0 &amp;\sim U(0, \infty)
\end{align}\]</span></p>
<p>The uniform prior in the standard deviation is incredibly vague and is considered a non-informative prior. Conversely, the <em>t</em> distribution (with two degrees of freedom) for the random effects reflects that we might expect that the distribution is symmetric but has heavy tails (e.g., potential outliers such as those seen in <a href="#fig-effect-encoding" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>(a)). Priors can be vague or highly opinionated.</p>
<p>When estimating the Bayesian model, the prior distributions are combined with the observed data to produce a <em>posterior distribution</em> for each parameter. Like the previous mixed-model technique, the posterior mimics the prior when there is very little (or noisy) data. The posterior distribution favors the observed results when high-quality data are abundant. Using Bayesian methods to estimate the effects enables much more versatility in specifying the model but is often more computationally intensive.</p>
</section>
<section id="non-guassian-outcomes" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="non-guassian-outcomes">Non-Guassian outcomes</h4>
<p>In many of these cases, effect encodings can be computed using Bayesian methods or via the <em>generalized linear mixed model</em> approach <span class="citation" data-cites="bolker2009generalized stroup2012generalized">(<a href="#ref-bolker2009generalized" role="doc-biblioref">Bolker et al. 2009</a>; <a href="#ref-stroup2012generalized" role="doc-biblioref">Stroup 2012</a>)</span> approach fitting a random intercept model.</p>
<p>The latter model has a similar right-hand side as <a href="#eq-effect-random-int" class="quarto-xref">Equation&nbsp;<span>6.2</span></a>. For example, when the outcome (<span class="math inline">\(y_{ij}\)</span>) is a count, the standard Poisson model would be</p>
<p><span class="math display">\[
\log(\mu_{ij}) = \beta_0 + \beta_{0j}
\]</span> where <span class="math inline">\(\mu_{ij}\)</span> is the theoretical effect in the original units.</p>
<p>Suppose the data are binomial proportions or Bernoulli (i.e., binary 0/1 values). The canonical effects model is:</p>
<p><span class="math display">\[
\log\left(\frac{\pi_{ij}}{1-\pi_{ij}}\right) = \beta_0 + \beta_{0j}
\]</span> with <span class="math inline">\(\pi_{ij}\)</span> being the parameter value for the effects. This is a basic logistic regression formulation of the problem.</p>
<p>Similar Bayesian approaches can be used. However, a completely different technique for binary outcomes is to assume again that the original data are binomial with rate parameter <span class="math inline">\(\pi\)</span> but, instead of the logistic regression formulation, assume that the actual rates come from a Beta distribution with parameters <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\gamma\)</span>. With the Beta distribution as the prior, users can specify distributions with different shapes, such as uniform, bell-shaped, or “U” shaped, depending on the values chosen for <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\gamma\)</span>. See <a href="https://www.bayesrulesbook.com/chapter-3.html">Chapter 3</a> of <span class="citation" data-cites="BayesRules">Johnson, Ott, and Dogucu (<a href="#ref-BayesRules" role="doc-biblioref">2022</a>)</span>. The Bayesian approach can be very flexible.</p>
</section>
<section id="consequences-of-using-effect-encodings" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="consequences-of-using-effect-encodings">Consequences of using effect encodings</h4>
<p>As with feature hashing, effect encoding methods can naturally handle novel categories in future data. Without knowing anything about the new category, the most logical choice for this method is to assign the overall population effect (e.g., the mode of the posterior distribution) as the value.</p>
<p>As with feature hashing, effect encodings can eliminate linear dependencies between sets of indicators. Since the categorical data are being replaced with numeric summaries of the outcome data, it may be likely that there is no longer a redundancy in the data. Indicator columns reflect the <em>identities</em> of the predictor categories, while the effect encoding column measures the <em>effectiveness</em> of the categories. For example, a hypothetical scenario was mentioned where the agent was aliased with the customer type, yielding a linear dependency. Once the agent name column is converted to effect estimates, there would no longer be a relationship between the two predictors.</p>
<p>Lastly, applying effect encodings requires a robust data usage strategy. The risk of embedding over-fitted statistics into the model could cause problems that may not be observed until a new data set is predicted (see <a href="overfitting.html" class="quarto-xref"><span>Chapter 9</span></a>). Using resampling methods or a validation set (<a href="resampling.html" class="quarto-xref"><span>Chapter 10</span></a>) is critical for using this tool. Also, when there is a temporal aspect to the data, we should try to ensure that historical data are not being predicted with future data (i.e., information leakage). For example, when an agent has multiple bookings, we kept the oldest data for an agent in the training set and newer bookings in the test set. Simple random sampling may result in the opposite occurring.</p>
</section>
</section>
<section id="sec-combining-categories" class="level3" data-number="6.4.4">
<h3 data-number="6.4.4" class="anchored" data-anchor-id="sec-combining-categories"><span class="header-section-number">6.4.4</span> Supervised Combining of Categories</h3>
<p>Another approach for dealing with predictors with large numbers of categories is to collapse them into smaller groups that similarly affect the outcome data. For example, a cluster of agents may have similar performance characteristics (i.e., mean ADRs). If we can derive clusters of categories from the training set, a smaller group of cluster-level indicators might be a better approach than many indicator columns.</p>
<p>This approach closely mirrors the splitting process in tree-based models (discussed in Sections <span class="quarto-unresolved-ref">?sec-cart-cls</span> and <span class="quarto-unresolved-ref">?sec-cart-reg</span>), and we can use these models to find suitable groupings of predictor values. In summary, the categories are ordered by their estimated effects and then partitioned into two groups by optimizing some performance measures. For classification models, this is usually a measure of the purity of the classes in the resulting partition<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>. A measure of error is used for numeric outcomes, such as RMSE. Once the initial partition is made, the process repeats recursively within each division until no more splits can be made, perhaps due to insufficient data.</p>
<p>For the agent data, <a href="#fig-collapse" class="quarto-xref">Figure&nbsp;<span>6.3</span></a> shows this process. The 122 agent are categorized into 12 groups. The top panel shows the ordered mean ADR values for each agent. The vertical lines indicate how the different agents are grouped at each step of the splitting process. The bottom panel shows a scaled estimate of the RMSE that uses the group-level mean ADR to predict the individual outcome results.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-collapse" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-collapse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../premade/anime_tree_collapse.gif" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-collapse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: The progression of using a tree-based method to collapse predictor categories into smaller sets.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For these data, there is no rational grouping or clustering of the agents (regarding their ADR) for the tree-based model to discover. The process produces increasingly granular groups, and the stopping point is somewhat arbitrary. For these reasons, it is probably not the best approach for this predictor in this particular data set.</p>
</section>
</section>
<section id="encodings-for-ordinal-predictors" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="encodings-for-ordinal-predictors"><span class="header-section-number">6.5</span> Encodings for Ordinal Predictors</h2>
<p>In some cases, a categorical predictor will have levels with an inherent order. For example, in the Ames data, some house amenities were ranked in terms of quality with values ‘<code>excellent</code>’, ‘<code>fair</code>’, ‘<code>good</code>’, ‘<code>typical</code>’, and ‘<code>poor</code>’. These values do not imply a specific numerical translation (e.g., ‘<code>excellent</code>’ = 2 times ‘<code>poor</code>’). For this reason, there are different options for converting them to numeric features.</p>
<p>First, the analysis could treat them as unordered categories and allow the model to try to determine how the values relate to the outcome. For example, if there is the belief that, as the quality of the heating system improves, the house price should increase. Using unordered categories would be agnostic to this assumption and the model would estimate whatever trend it saw in the data. This approach would essentially be treating the quality variable as a categorical variable with 5 levels.</p>
<p>Another choice is to use domain-specific knowledge to imply relationships between levels. For example, the quality values could be replaced with integers one through five. This does bake the assumed relationship into the features, and that is advantageous when the assumed pattern is correct.</p>
<p>There are also contrast methods, similar to the one discussed in <a href="#sec-indicators" class="quarto-xref"><span>Section 6.2</span></a>, that can automatically create potential patterns using polynomial expansions (more on these in <a href="interactions-nonlinear.html#sec-polynomials" class="quarto-xref"><span>Section 8.2</span></a>). For our quality example, there are five possible levels. Mathematically, we can create up to the number of unique levels (minus one) polynomial function. In this example, linear, quadratic, cubic, and quartic (<span class="math inline">\(x^4\)</span>) polynomial functions can be used. <a href="#fig-ordered" class="quarto-xref">Figure&nbsp;<span>6.4</span></a> shows these patterns using orthogonal polynomial values<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ordered" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ordered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../figures/fig-ordered-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ordered-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Polynomial contrasts for an ordered categorical predictor with five possible levels.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In many applications, higher-degree polynomials (&gt; 2) are unlikely to be effective predictors. For example, the cubic pattern in <a href="#fig-ordered" class="quarto-xref">Figure&nbsp;<span>6.4</span></a> (“Feature 3”) implies that houses in Ames with ‘<code>excellent</code>’ quality heating systems would have lower sale prices than those with ‘<code>fair</code>’ or ‘<code>poor</code>’ systems. Utilizing higher order polynomials usually requires some specific knowledge about the problem at hand.</p>
</section>
<section id="chapter-references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="chapter-references">Chapter References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ANTONIO201941" class="csl-entry" role="listitem">
Antonio, N, A de Almeida, and L Nunes. 2019. <span>“<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=Hotel+booking+demand+datasets&amp;as_ylo=2019&amp;as_yhi=2019&amp;btnG=">Hotel Booking Demand Datasets</a>.”</span> <em>Data in Brief</em> 22: 41–49.
</div>
<div id="ref-bolker2009generalized" class="csl-entry" role="listitem">
Bolker, B, M Brooks, C Clark, S Geange, J Poulsen, H Stevens, and JS White. 2009. <span>“<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=Generalized+linear+mixed+models+A+practical+guide+for+ecology+and+evolution&amp;as_ylo=2009&amp;as_yhi=2009&amp;btnG=">Generalized Linear Mixed Models: A Practical Guide for Ecology and Evolution</a>.”</span> <em>Trends in Ecology and Evolution</em> 24 (3): 127–35.
</div>
<div id="ref-BHH" class="csl-entry" role="listitem">
Box, GEP, W Hunter, and J. Hunter. 1978. <em>Statistics for Experimenters</em>. New York: Wiley.
</div>
<div id="ref-Cerda2022" class="csl-entry" role="listitem">
Cerda, P, and G Varoquaux. 2022. <span>“<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=Encoding+High+Cardinality+String+Categorical+Variables&amp;as_ylo=2022&amp;as_yhi=2022&amp;btnG=">Encoding High-Cardinality String Categorical Variables</a>.”</span> <em>IEEE Transactions on Knowledge and Data Engineering</em> 34 (3): 1164–76.
</div>
<div id="ref-demidenko2013mixed" class="csl-entry" role="listitem">
Demidenko, E. 2013. <em>Mixed Models: Theory and Applications with <span>R</span></em>. John Wiley &amp; Sons.
</div>
<div id="ref-EfronHastie2016a" class="csl-entry" role="listitem">
Efron, B, and T Hastie. 2016. <em><a href="https://hastie.su.domains/CASI/">Computer Age Statistical Inference</a></em>. Cambridge University Press.
</div>
<div id="ref-estimable" class="csl-entry" role="listitem">
Elswick, RK, C Gennings, V Chinchilli, and K Dawson. 1991. <span>“<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=A+Simple+Approach+for+Finding+Estimable+Functions+in+Linear+Models&amp;as_ylo=1991&amp;as_yhi=1991&amp;btnG=">A Simple Approach for Finding Estimable Functions in Linear Models</a>.”</span> <em>The American Statistician</em> 45 (1): 51–53.
</div>
<div id="ref-gelman1995bayesian" class="csl-entry" role="listitem">
Gelman, A, J Carlin, H Stern, and D Rubin. 2013. <em>Bayesian Data Analysis</em>. Chapman; Hall/CRC.
</div>
<div id="ref-BayesRules" class="csl-entry" role="listitem">
Johnson, A, M Ott, and M Dogucu. 2022. <em>Bayes Rules!: An Introduction to Applied Bayesian Modeling</em>. Chapman; Hall/CRC.
</div>
<div id="ref-kruschke2014doing" class="csl-entry" role="listitem">
Kruschke, J. 2014. <em>Doing <span>Bayesian</span> Data Analysis: A Tutorial with <span>R</span>, <span>JAGS</span>, and <span>Stan</span></em>. Academic Press.
</div>
<div id="ref-laird1982random" class="csl-entry" role="listitem">
Laird, N, and J Ware. 1982. <span>“<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=Random+effects+models+for+longitudinal+data&amp;as_ylo=1982&amp;as_yhi=1982&amp;btnG=">Random-Effects Models for Longitudinal Data</a>.”</span> <em>Biometrics</em>, 963–74.
</div>
<div id="ref-Rethinking" class="csl-entry" role="listitem">
McElreath, R. 2015. <em>Statistical Rethinking: A <span>Bayesian</span> Course with Examples in <span>R</span> and <span>Stan</span></em>. Chapman; Hall/CRC.
</div>
<div id="ref-MicciBarreca2001" class="csl-entry" role="listitem">
Micci-Barreca, D. 2001. <span>“<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=A+preprocessing+scheme+for+high+cardinality+categorical+attributes+in+classification+and+prediction+problems&amp;as_ylo=2001&amp;as_yhi=2001&amp;btnG=">A Preprocessing Scheme for High-Cardinality Categorical Attributes in Classification and Prediction Problems</a>.”</span> <em>ACM SIGKDD Explorations Newsletter</em> 3 (1): 27–32.
</div>
<div id="ref-pargent2022regularized" class="csl-entry" role="listitem">
Pargent, F, F Pfisterer, J Thomas, and B Bischl. 2022. <span>“<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=Regularized+target+encoding+outperforms+traditional+methods+in+supervised+machine+learning+with+high+cardinality+features&amp;as_ylo=2022&amp;as_yhi=2022&amp;btnG=">Regularized Target Encoding Outperforms Traditional Methods in Supervised Machine Learning with High Cardinality Features</a>.”</span> <em>Computational Statistics</em>, 1–22.
</div>
<div id="ref-ruberg" class="csl-entry" role="listitem">
Ruberg, S. 1989. <span>“<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=Contrasts+for+Identifying+the+Minimum+Effective+Dose&amp;as_ylo=1989&amp;as_yhi=1989&amp;btnG=">Contrasts for Identifying the Minimum Effective Dose</a>.”</span> <em>Journal of the American Statistical Association</em> 84 (407): 816–22.
</div>
<div id="ref-stroup2012generalized" class="csl-entry" role="listitem">
Stroup, W. 2012. <em>Generalized Linear Mixed Models: Modern Concepts, Methods and Applications</em>. CRC press.
</div>
<div id="ref-weinberger2009feature" class="csl-entry" role="listitem">
Weinberger, K, A Dasgupta, J Langford, A Smola, and J Attenberg. 2009. <span>“<a href="https://scholar.google.com/scholar?hl=en&amp;as_sdt=0%2C7&amp;q=Feature+hashing+for+large+scale+multitask+learning&amp;as_ylo=2009&amp;as_yhi=2009&amp;btnG=">Feature Hashing for Large Scale Multitask Learning</a>.”</span> In <em>Proceedings of the 26th Annual International Conference on Machine Learning</em>, 1113–20. ACM.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>In other words, we know that the vector of indicators (0, 0, 0) must represent the contract customers.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This is discussed in greater detail for one of the case studies in <span class="quarto-unresolved-ref">?sec-reg-summary</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The original data uses codes to anonymize the agent names. The names shown here are randomly fabricated. The same is true of the company names.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Also called <em>target encoding</em> or <em>likelihood encoding</em>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>This demonstrates the concept of <em>overfitting</em>, discussed in <a href="overfitting.html" class="quarto-xref"><span>Chapter 9</span></a> and subsequent chapters.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>In the language of mixed effects models, the agent is a <em>fixed effect</em> in this parameterization.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><a href="#eq-effect-posterior" class="quarto-xref">Equation&nbsp;<span>6.3</span></a> is related to the well-known James-Stein estimator <span class="citation" data-cites="EfronHastie2016a">(<a href="#ref-EfronHastie2016a" role="doc-biblioref">Efron and Hastie 2016, chap. 7</a>)</span>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Making the range of the prior exceedingly wide indicates that almost any value is possible.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>In other words, a very narrow distribution. There are other ways to create opinionated priors though. For instance, a skewed prior distribution for one of the <span class="math inline">\(\beta\)</span> regression slopes would be considered opinionated.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>The linear mixed model approach mentioned above is often considered as an <em>empirical Bayes</em> approach with more restrictive options for the prior distributions. For empirical Bayes, one might say that you make your priors for your regression parameters any distribution you want, as long as they are Gaussians.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>The notion of “purity” can mean a very tight distribution of numerical data (for regression models) or when the frequency distribution of qualitative has a very high probability for one category.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>These features have characteristics that their values sum to zero and there is zero correlation between features.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/aml4td\.org");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/numeric-predictors.html" class="pagination-link" aria-label="Transforming Numeric Predictors">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transforming Numeric Predictors</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/embeddings.html" class="pagination-link" aria-label="Embeddings">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Embeddings</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script src="https://cdn.jsdelivr.net/npm/pseudocode@latest/build/pseudocode.min.js" type="text/javascript"></script>
<script type="text/javascript">
(function(d) {
  d.querySelectorAll(".pseudocode-container").forEach(function(el) {
    let pseudocodeOptions = {
      indentSize: el.dataset.indentSize || "1.2em",
      commentDelimiter: el.dataset.commentDelimiter || "//",
      lineNumber: el.dataset.lineNumber === "true" ? true : false,
      lineNumberPunc: el.dataset.lineNumberPunc || ":",
      noEnd: el.dataset.noEnd === "true" ? true : false,
      titlePrefix: el.dataset.algTitle || "Algorithm"
    };
    pseudocode.renderElement(el.querySelector(".pseudocode"), pseudocodeOptions);
  });
})(document);
(function(d) {
  d.querySelectorAll(".pseudocode-container").forEach(function(el) {
    titleSpan = el.querySelector(".ps-root > .ps-algorithm > .ps-line > .ps-keyword")
    titlePrefix = el.dataset.algTitle;
    titleIndex = el.dataset.chapterLevel ? el.dataset.chapterLevel + "." + el.dataset.pseudocodeIndex : el.dataset.pseudocodeIndex;
    titleSpan.innerHTML = titlePrefix + " " + titleIndex + " ";
  });
})(document);
</script>




</body></html>