name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
          tinytex: false
      
      - name: Render Quarto Project
        shell: bash
        env:
          GH_PAGES: gh-pages
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          quarto render
          git fetch origin "${GH_PAGES}"
          git checkout origin/"${GH_PAGES}" -- preview
          mv preview _book/
          quarto publish gh-pages --no-prompt --no-render --no-browser
